2.5.0:  Fix TypeError when clicking on document
Prior to this fix, the following error would be intermittently generated
when clicking close to a VirtualHelix:

```
Traceback (most recent call last):
  File "cadnano/gui/views/sliceview/nucleicacidpartitem.py", line 591, in mousePressEvent
    getattr(self, tool_method_name)(tool, event)
  File "cadnano/gui/views/sliceview/nucleicacidpartitem.py", line 658, in createToolMousePress
    pt = tool.eventToPosition(self, event)
  File "cadnano/gui/views/sliceview/tools/abstractslicetool.py", line 151, in eventToPosition
    QPointF(_RADIUS - DELTA, _RADIUS - DELTA))
TypeError: unsupported operand type(s) for -: 'NoneType' and 'QPointF'
Abort trap: 6
```

This was caused by returning `None` in abstractslicetool's `findNearestPoint`.