Fix editing of the VirtualHelix 'z' Property
* cadnano/gui/views/propertyview/virtualhelixitem.py:
    AttributeError: 'VirtualHelixSetItem' object has no attribute '_model_part'
    + 'self._model_part' changed to 'cn_m.part()'

    NameError: name 'cm' is not defined
    + 'cm' changed to 'cn_m'

* cadnano/part/virtualhelix.py:
    AttributeError: 'VirtualHelix' object has no attribute 'getZ'
    + Defined a getZ method to return the current 'z' property value for
      the VirtualHelix corresponding to the given ID number

    Iteration issue in setZ:
    - If id_nums is not set when calling setZ, the setZ method sets
      id_nums to self._id_num.  This will be problematic as the method
      goes on to iterate over id_nums, and self._id_num (which
      corresponds to an interger) is not iterable.  This may actually
      cause an exception, but this bug was fixed at the same time as
      getZ implementation, so no exception was seen by the developer for
      this bug
    + If id_nums is None, set id_nums to be a list of one element
      corresponding to the VirtualHelix's id_num

Also add spacing between 3p and local/library imports per PEP-8

Closes #96